name: GeoSci JSON Building Blocks repository

abstract: |
  Repository assembling building blocks for geoscience JSON metadata, using OGC building block patterns.
description: |
  Modular JSON Schema building blocks for geoscience metadata and profiles.

identifier-prefix: usgin.bbr.geosci.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: True

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore
